// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo2YLU3mPVjU4NB_GdJESEYG2BtaW-OY8',
    appId: '1:78287006663:android:752be634d5d074833b07e2',
    messagingSenderId: '78287006663',
    projectId: 'mynotesapp-843b5',
    storageBucket: 'mynotesapp-843b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwdE0PMF42HWR50j1Zh9rfmaD5LMCVu98',
    appId: '1:78287006663:ios:550da4f740d81efd3b07e2',
    messagingSenderId: '78287006663',
    projectId: 'mynotesapp-843b5',
    storageBucket: 'mynotesapp-843b5.appspot.com',
    iosBundleId: 'com.mynotesapp.mynotesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwdE0PMF42HWR50j1Zh9rfmaD5LMCVu98',
    appId: '1:78287006663:ios:550da4f740d81efd3b07e2',
    messagingSenderId: '78287006663',
    projectId: 'mynotesapp-843b5',
    storageBucket: 'mynotesapp-843b5.appspot.com',
    iosBundleId: 'com.mynotesapp.mynotesapp',
  );
}
